function com_blackout_solarpanelcalculator(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',kc='.cache.html',_='/',lb='//',Zb='02F9251DADBC987862DAC422573862F7',$b='12F736DAD66721E07CBAF26CAC81E11B',_b='29F7C46E293A03229243EDBDA7A4F210',ac='4146727595940E70A2247D1D9A6D5A69',bc='4B22934ACB52AB92FF9AA4967FDD9C0A',cc='641424363A7EDC018C1999CF4E18F728',dc='648F0F66309856760F7049B210401C72',ec='7B08432AD0C323FD8E12F482B747ED0A',fc='8D01CD87854C42E59E9EE6232757CA51',jc=':',pb='::',sc='<script defer="defer">com_blackout_solarpanelcalculator.onInjectionDone(\'com_blackout_solarpanelcalculator\')<\/script>',hb='<script id="',sb='=',$='?',gc='ACB2FF297856EE09BFF15250A978EBBB',ub='Bad handler "',hc='D5E43E66A0E4CFEE104E9946CD80A966',rc='DOMContentLoaded',ic='F2A281D01E52244E443F5BA24370C17A',Gb='Gears.Factory',jb='SCRIPT',gb='__gwt_marker_com_blackout_solarpanelcalculator',Ib='application/x-googlegears',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',Q='com_blackout_solarpanelcalculator',eb='com_blackout_solarpanelcalculator.nocache.js',ob='com_blackout_solarpanelcalculator::',rb='content',Y='end',Db='function',Fb='gears',Tb='gecko',Ub='gecko1_8',Cb='geolocation.api',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',lc='gwt/clean/clean.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',qc='head',Xb='hosted.html?com_blackout_solarpanelcalculator',pc='href',Eb='html5',Sb='ie6',Rb='ie8',Qb='ie9',Hb='ie_mobile',yb='iframe',ab='img',zb="javascript:''",mc='link',Wb='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Pb='msie',nb='name',Kb='none',Jb='object',Mb='opera',Ab='position:absolute;width:0;height:0;border:none',nc='rel',Ob='safari',db='script',Yb='selectingPermutation',R='startup',oc='stylesheet',fb='undefined',Vb='unknown',Lb='user.agent',Nb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}com_blackout_solarpanelcalculator=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){if(typeof navigator.geolocation!=fb&&typeof navigator.geolocation.getCurrentPosition==Db){return Eb}if(window.google&&google.gears){return Fb}var b=null;if(typeof GearsFactory!=fb){b=new GearsFactory}else{try{b=new ActiveXObject(Gb);if(b.getBuildInfo().indexOf(Hb)!=-1){b.privateSetGlobalObject(this)}}catch(a){if(typeof navigator.mimeTypes!=fb&&navigator.mimeTypes[Ib]){b=document.createElement(Jb);b.style.display=Kb;b.width=0;b.height=0;b.type=Ib;document.documentElement.appendChild(b)}}}if(!b){return Eb}if(!window.google){google={}}if(!google.gears){google.gears={factory:b}}return Fb};v[Cb]={gears:0,html5:1};w[Lb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Mb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1}())return Ob;if(function(){return b.indexOf(Pb)!=-1&&n.documentMode>=9}())return Qb;if(function(){return b.indexOf(Pb)!=-1&&n.documentMode>=8}())return Rb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Sb;if(function(){return b.indexOf(Tb)!=-1}())return Ub;return Vb};v[Lb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};com_blackout_solarpanelcalculator.onScriptLoad=function(){if(I){r=true;C()}};com_blackout_solarpanelcalculator.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Xb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Yb});if(!B()){try{G([Fb,Ub],Zb);G([Eb,Ob],$b);G([Eb,Rb],_b);G([Eb,Ub],ac);G([Fb,Sb],bc);G([Eb,Mb],cc);G([Fb,Mb],dc);G([Fb,Rb],ec);G([Fb,Qb],fc);G([Eb,Qb],gc);G([Fb,Ob],hc);G([Eb,Sb],ic);K=x[H(Cb)][H(Lb)];var M=K.indexOf(jc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+kc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[lc]){var a=n.createElement(mc);__gwt_stylesLoaded[lc]=a;a.setAttribute(nc,oc);a.setAttribute(pc,t+lc);n.getElementsByTagName(qc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(rc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(rc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Wb,millis:(new Date).getTime(),type:T});n.write(sc)}
com_blackout_solarpanelcalculator();